name: WhiteSource Vulnerability Scan

on:
#  schedule:
#    - cron: '30 10 * * *'
  repository_dispatch:
    types: [check-vulnerability-whitesource]
  workflow_dispatch

jobs:
  whitesource-vulnerability-scan:
    name: WhiteSource Vulnerability Scan
    runs-on: Ubuntu-18.04
    outputs:
      mail_content_output: ${{ steps.vulnerability_scan.outputs.mail_content }}
    strategy:
      fail-fast: false
      matrix:
        java: [14]
        go-version: [1.14]
    steps:
      - uses: actions/checkout@v1
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v1
      - name: Vulnerability Scan
        id: vulnerability_scan
        env:
          wss_apikey: ${{ secrets.WSS_API_KEY }}
        run: |
          export PATH=$JAVA_HOME:$PATH
          cd standalone-tools/vulnerability-scan
          sudo yum install -y maven
          wget -q https://services.gradle.org/distributions/gradle-6.7-bin.zip
          sudo mkdir /opt/gradle
          sudo unzip -d /opt/gradle gradle-6.7-bin.zip
          wget -qO - https://rpm.nodesource.com/setup_14.x | sudo bash -
          sudo yum install -y nodejs
          wget -qO - https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
          sudo rpm --import https://dl.yarnpkg.com/rpm/pubkey.gpg
          sudo yum install yarn -y
          export PATH=$PATH:/opt/gradle/gradle-6.7/bin
          gradle -v; mvn -v ; npm -v; yarn -v
          # This step is needed to avoid build failures in few plugins
          # No ETA on when this dependency can be removed
          git clone https://github.com/opensearch-project/OpenSearch.git
          cd OpenSearch
          gradle publishToMavenLocal; cd ..
          ./wss-scan.sh
          echo ::set-output name=mail_content::$(cat output.md)
          cat whitesource/*/*
